#==============================================================
#
#  Abs: Install ChannelWatcher save/restore files for bumpless reboot
#
#  Facility: PLC Administration
#
#  Auth: 24-Jan-2014, Kristi Luchini  (USERNAME)
#  Rev:  dd-mmm-yyyy, Reviewers Name  (USERNAME)
#--------------------------------------------------------------
#  Mod:
#        dd-mmm-yyyy, First Lastname  (USERNAME):
#           comment
#
#============================================================== 
#
TOP = ../..
include $(TOP)/configure/CONFIG
#----------------------------------------
#  ADD MACRO DEFINITIONS AFTER THIS LINE
#
# Rules for installing ChannelWatcher files:
CFG += CONFIG_RESTORE

# Install config files
RESTORES += plcAdminControlLogix.cwConfig

include $(TOP)/configure/RULES
#----------------------------------------
#  ADD RULES AFTER THIS LINE
#
# End of File

